### ISSUE TITLE
Base encoding is incorrect

### ISSUE THREAD

**Issue by jbenet** [ipld/js-cid#13]
The current implementation of `toBaseEncodedString()` is https://github.com/ipld/js-cid/blob/185625002b248771a3586aac0800323102cd5e2c/src/index.js#L96-L107 -- this is incorrect.

It should be:

```js
  toBaseEncodedString (base) {
    base = base || 'base58btc'

    switch (this.version) {
      case 0:
      case 1:
        return multibase.encode(base, this.buffer).toString()
      default:
        throw new Error('Unsupported version')
    }
  }
```
both `case 0` and `case 1` should return the proper base encoded version, and should return a CIDv1 link. if we _want_ to enable returning a CIDv0 link, that should be an explicit flag or a different function. otherwise it leads to incorrect and confusing behavior. 

Consider this:

```
> var hash = 'QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB'
> var CID = require('cids')
> var id = new CID(hash)
> console.log(id.toBaseEncodedString('base16'))
"QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB"
```

That's totally borked. like mega borked. 

BTW, we NEED to be able to express old CIDv0 links as the new CIDv1 links, particularly for browser support where the "host" part of the URI MUST be case insensitive (this is needed to support `ipfs://<hash>` which is needed because people cannot specify the origin to browsers, but MUST give it in the URI. we dont want `ipfs` to be the origin, we want `<hash>` or `<name>`. so this means only base32 or base16 hashes there. thanks to origin policy).

**Comment by jbenet** [comment]
HT to @gozala, who found this problem in the first place. Sorry you ran into this! :(

**Comment by dignifiedquire** [comment]
Thank you @jbenet, will push a fix later today.

**Comment by Gozala** [comment]
Any plans to publish fixed version to npm ?

**Comment by diasdavid** [comment]
@Gozala would love your comments on https://github.com/ipld/js-cid/pull/14#discussion_r97047289.

**Comment by diasdavid** [comment]
C&P https://github.com/ipld/js-cid/pull/14#issuecomment-275144753

> The issues presented through the https://github.com/ipld/js-cid/pull/14 PR have been addressed in:
> - https://github.com/ipld/js-cid/pull/16
> - https://github.com/ipld/js-cid/pull/17
> Me and @gozala also had a good chat on IRC and a lot of clarification on how it works has been provided. An example was added as well.

**Comment by diasdavid** [comment]
Going to close this issue, fixes were merged and released. Let me know if there is any other question.
