### ISSUE TITLE
README has some methods which are missing

### ISSUE THREAD

**Issue by mitar** [ipld/js-cid#23]
I tried methods and properties listed in README and some are missing:
* `hash`
* `prefix`

**Comment by diasdavid** [comment]
Sorry about that, it is in fact `multihash` and not `hash` and prefix is not a method, just a property, updated the readme now https://github.com/ipld/js-cid/commit/fe344b67d22fa71477d52900bca96a7cf8cfdf82

**Comment by mitar** [comment]
Thanks!
