### ISSUE TITLE
description

### ISSUE THREAD

**Issue by noffle** [ipld/js-cid#3]
If I'm any indication, readers might not know what a CID is. It might be worth mentioning briefly what this module does and any necessary background context required.

**Comment by dignifiedquire** [comment]
Waiting on the spec to be written, so I can link to it. For now there is only https://github.com/ipfs/specs/issues/130

**Comment by diasdavid** [comment]
There is a description now \o/ hope it helps :) https://github.com/ipfs/js-cid

This is the spec 'we have' https://github.com/ipfs/specs/issues/130

**Comment by noffle** [comment]
@diasdavid My eyes fail me -- where? I read the README and still don't know what a CID is. :grinning:

**Comment by diasdavid** [comment]
@noffle, I know this took a while, but now you should be able to get a good picture of what CID is at its spec: https://github.com/ipld/cid thank you for pushing this :)
