### ISSUE TITLE
CIDs with dag-cbor formats as V0 addresses

### ISSUE THREAD

**Issue by vmatekole** [ipld/js-cid#35]
I'm trying to retrieve a DAG persisted with the following options via webui. As I understand it, to do so I have to convert to a V0 address as per — https://github.com/ipld/js-cid/blob/38e5dd0f5e89a750d9f20efefdaa00d38b287739/test/index.spec.js#L81 :
```  const dagOpts = { format: 'dag-cbor', hashAlg: 'sha3-512' }; ```

I have the following code that results in an error —  'Cannot convert a non dag-pb CID to CIDv0' :
``` 
      let cid  = new CID("zdpuAypJXbmGCLweJBL6R1iBpDGJyP8LU1BwZjzRjwNxohzvE");
     console.log(cid.toV0());
```

Is it possible at all to access objects of format ```dag-cbor``` type from webui or IPFS cli?

**Comment by diasdavid** [comment]
CIDv0 is dag-pb, sha2-256 and base58 only. CIDv0 is "pre CID era", to use dag-cbor, any other hash func or any other base you need to use CIDv1 or above. See: https://github.com/ipld/cid

I bet that probably what you need is for the HTTP API to support the DAG API properly. Please see:
- spec: https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag
- impl state on js-ipfs-api: https://github.com/ipfs/js-ipfs-api/pull/534
- examples in js-ipfs: https://github.com/ipfs/js-ipfs/tree/master/examples/dag

**Comment by diasdavid** [comment]
@vmatekole did the above answer your question?

**Comment by vmatekole** [comment]
Hi @diasdavid, only just got your response. Will take a look and respond at my earliest.

**Comment by diasdavid** [comment]
Closing for now, @vmatekole if you have any other questions.
