### ISSUE TITLE
multicodec needs to be validated

### ISSUE THREAD

**Issue by realharry** [ipld/js-cid#46]
Calling cid.buffer property throws the following exception when version==1:

     Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
      at fromObject (buffer.js:262:9)
      at Function.Buffer.from (buffer.js:101:10)
      at CID.get buffer [as buffer] (/home/harry/.../js-ipfs/node_modules/cids/src/index.js:122:18)
 
## How to reproduce

* Create a CID object with version==1. 
* Call cid.buffer.

**Comment by realharry** [comment]
This was due to the fact that I was passing in an "invalid" codec. CID class itself does not seem to have any notion of what is valid and what is not valid when it comes to codec. (e.g., there is no error checking.) But, if you construct a CID object with "invalid" codec (not supported by `multicodec/src/varint-table`, for instance), then the `CID.buffer` property call will fail since the argument of Buffer.from() will be invalid.

**Comment by diasdavid** [comment]
Thanks for the diagnostic, @realharry :)

**Comment by vmx** [comment]
This is fixed and confirmed by the merge of https://github.com/ipld/js-cid/pull/47.
